# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14aaf1a3a5d8ae260ae0ae730258dad9b7c1defaf030e92792e77148a08130c62ac1cc764fcddf79f3019ea5dbe12e998687ade8ae2b5acaad8d91324a6530c2

test:
  secret_key_base: 04d0b65b3b0c420ae1ea3455a7b4321778bf55685b0c2b2922c77346d624220104c1c4d13c559602e83af59508932cf4bd32e582727d425d251e4085c5d98a23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
